"""A model-generated self-test suite cannot condemn a candidate.

The cases are generated by the same model that writes the candidates, and
for these tasks producing an expected output IS solving the problem. So a
wrong answer key and wrong code are indistinguishable from the score.

Measured across a 28-session run: 0 of 44 candidates passed the sandbox,
with scores of 0/5, 0/4, 0/3 and never a partial. The check rejected every
candidate it saw, which is not evidence — and it cost the pipeline every
winner it might have had, since every passing session in every run was won
by the model's own direct write rather than by a V3 candidate.

So every case carries its provenance, and the pipeline records a generated
suite's score as a diagnostic (`self_test_untrusted`) and never rejects a
candidate on it.
"""

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "v3-service"))

import pipeline


def test_the_untrusted_stage_is_registered():
    """An unregistered stage contributes no phase row, so the run summary
    loses the record that a score was observed and given no authority."""
    assert pipeline._STAGE_PHASE["self_test_untrusted"] == "self_test"


# --- a suite is trusted by provenance, never by its score ------------------
#
# The cases come from the same model as the candidate, written from the
# problem statement alone, and for these tasks producing the expected output
# IS solving the problem. Measured on the captured pool: 21 of 36 valid
# generated keys disagreed with the task's own reference, 4 of them holding
# the model's reasoning transcript instead of an answer, and the ring2
# candidate that matched the reference on every input scored 2/5 against its
# own suite. A suite like that may be recorded; it may not decide.

import sys as _sys
from pathlib import Path as _Path
from types import SimpleNamespace as _NS

_sys.path.insert(0, str(_Path(__file__).resolve().parents[2] / "v3-service"))

from stages import self_test_gen as _stg


def _generated(inp, exp):
    return _stg.GeneratedTestCase(input_str=inp, expected_output=exp)


def _trusted(inp, exp):
    return _stg.GeneratedTestCase(input_str=inp, expected_output=exp,
                                  provenance=_stg.PROVENANCE_TRUSTED)


def test_the_generator_marks_every_case_it_produces():
    """At the creation point, not somewhere downstream."""
    cases = _stg.SelfTestGen(_stg.SelfTestGenConfig(enabled=True)).parse_test_cases(
        "TEST CASE 1:\nINPUT: 1\nOUTPUT: 2\n\nTEST CASE 2:\nINPUT: 3\nOUTPUT: 4\n")
    assert len(cases) == 2
    assert all(c.provenance == _stg.PROVENANCE_GENERATED for c in cases)
    assert all(c.to_dict()["provenance"] == _stg.PROVENANCE_GENERATED
               for c in cases)


def test_generated_cases_are_not_an_oracle():
    assert pipeline._trusted_oracle(_NS(test_cases=[_generated("1", "2")])) is False


def test_trusted_cases_are_an_oracle():
    assert pipeline._trusted_oracle(_NS(test_cases=[_trusted("1", "2")])) is True


def test_unknown_provenance_fails_closed():
    """A case that cannot say where it came from gets no authority; a future
    producer opts in deliberately rather than inheriting trust by omission."""
    assert pipeline._trusted_oracle(
        _NS(test_cases=[_NS(input_str="1", expected_output="2")])) is False
    assert pipeline._trusted_oracle(
        _NS(test_cases=[_NS(input_str="1", expected_output="2",
                            provenance=None)])) is False
    assert pipeline._trusted_oracle(
        _NS(test_cases=[_NS(input_str="1", expected_output="2",
                            provenance="looks-trusted")])) is False
    # One untrusted case in an otherwise trusted suite disqualifies it.
    assert pipeline._trusted_oracle(
        _NS(test_cases=[_trusted("1", "2"), _generated("3", "4")])) is False


def test_no_suite_at_all_is_not_an_oracle():
    assert pipeline._trusted_oracle(None) is False
    assert pipeline._trusted_oracle(_NS(test_cases=[])) is False


def test_a_reasoning_transcript_key_has_no_authority():
    """The measured shape: the model kept writing after the answer and the
    whole continuation became the expected output."""
    transcript = ("12 a\n\nWait, let me re-calculate Case 5 carefully:\n"
                  "Total rejections = 3.\nCorrect output: 3 a")
    assert pipeline._trusted_oracle(
        _NS(test_cases=[_generated("0 a", transcript)])) is False


def test_a_placeholder_input_has_no_authority():
    assert pipeline._trusted_oracle(
        _NS(test_cases=[_generated("(empty file)", "0")])) is False
